---
title: "ecoreg_para_richness"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(magrittr)


library(sf)
library(tmap)
```

```{r}
ecoregions <- sf::st_read("/Users/danielsuh/Desktop/Terrestrial_Ecoregions/Terrestrial_Ecoregions.shp")
gmpd <- read_csv(here("data", "GMPD", "GMPD_main.csv"))
```

```{r}
gmpd %<>% drop_na(., Longitude, Latitude) %>% st_as_sf(., coords=c("Longitude", "Latitude"), crs = "WGS84")
ecoregions %<>% st_transform(crs="WGS84")

sf_use_s2(FALSE)
```

```{r}
head(ecoregions) %>% st_simplify() %>% tm_shape(.) + tm_borders()
```



```{r}
gmpd_ecoregions <- st_intersection(gmpd, ecoregions)
```

```{r}
para_pres_ecoreg <- gmpd_ecoregions %>% 
  st_drop_geometry() %>% #remove geom to make attribute manipulation much faster
  dplyr::select(ECO_CODE, ParasiteCorrectedName) %>% #just get ecoregions and host names
  mutate(pres = 1) %>% #just a placeholder value to show that there was a presence
  distinct() #sometimes there are duplicates because there were multiple polygons for one host for one ecoregion
```

```{r}
ecoreg_para_mat <- para_pres_ecoreg %>% pivot_wider(., names_from = ECO_CODE, values_from = pres) 
ecoreg_para_mat %<>% replace(is.na(.), 0)
```


Ecoregion study effort - how many gmpd studies per ecoregion
```{r}
gmpd_ecoreg_effort <- gmpd_ecoregions %>% 
  st_drop_geometry() %>%
  dplyr::select(Citation, ECO_CODE) %>%
  distinct() %>% 
  group_by(ECO_CODE) %>%
  summarize(n = n())
```



```{r}
saveRDS(ecoreg_para_mat, file = here("data", "processed_data", "ecoreg_para_mat.rds"))
saveRDS(gmpd_ecoreg_effort, file = here("data", "processed_data", "gmpd_ecoreg_effort.rds"))
```





