---
title: "para_regression"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(magrittr)
```


```{r}
host_para_mat <- readRDS(here("data", "processed_data", "para_mat.rds"))
ecoreg_host_mat <- readRDS(here("data", "processed_data", "ecoreg_mat.rds"))
ecoreg_para_mat <- readRDS(here("data", "processed_data", "ecoreg_para_mat.rds"))
null_para_df <- readRDS(here("data", "processed_data", "null_para_df.rds"))
gmpd_ecoreg_effort <- readRDS(here("data", "processed_data", "gmpd_ecoreg_effort.rds"))
```


```{r}
null_prop <- seq(0.05, 1, by = 0.05)
```



```{r}
para_df_list <- list()
for(i in 1:length(null_prop)){
 para_df_list[[i]] <- null_para_df %>% 
   group_by(sci_name, para) %>% 
   slice_sample(prop = null_prop[i]) %>% 
   ungroup()
}

names(para_df_list) <- null_prop

```



```{r, make mat}
make_mat <- function(para_df){
para_df %>% 
  dplyr::select(c(para, name, value)) %>% 
  distinct() %>% 
  pivot_wider(., names_from = name, values_from = value) %>%
  replace(is.na(.), 0)
}

para_mat_list <- lapply(para_df_list, make_mat)
```


Null regression

100% coverage
```{r}
host_rich <- colSums(ecoreg_host_mat[2:ncol(ecoreg_host_mat)])
host_rich_df <- tibble(ecoreg = names(host_rich), host = host_rich)
```

```{r}
get_richness_df <- function(para_mat){
  para_rich <- colSums(para_mat[2:ncol(para_mat)])
  
  tmp <- tibble(para = para_rich, ecoreg = names(para_rich))
  
  tmp %>% left_join(., host_rich_df) %>% replace(is.na(.), 0)
}
```


```{r}
null_richness_list <- lapply(para_mat_list, get_richness_df)
```



```{r}
get_lm <- function(df){
  lm(para ~ host, df)
}

lm_list <- lapply(null_richness_list, get_lm)
```

```{r}
null_plots <- list()
for(i in 1:length(null_richness_list)){
  null_plots[[i]] <- null_richness_list[[i]] %>% ggplot(., aes(x=host, y=para)) + geom_point() + geom_smooth(method = "lm") + labs(title = names(null_richness_list[i])) + xlim(0,65) + ylim(0,270)
}
```

```{r}
null_plots
```

```{r}
lapply(lm_list, coef)
```




Actual regression

```{r}
actual_para_rich <- get_richness_df(ecoreg_para_mat)
```


```{r}
actual_para_rich %>% filter(para>0) %>% ggplot(.,aes(x=host, y=para)) + geom_point() + geom_smooth(method="lm")

summary(lm(para ~ host, data = actual_para_rich))
```