---
title: "pdp"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
library(tidyverse)
library(magrittr)

library(dismo)
library(gbm)
library(pdp)
library(cowplot)
library(patchwork)
library(pROC)

source(here("elith_tutorial", "brt.functions.R"))
```

```{r}
brt_mod <- readRDS(file = here("data", "processed_data", "brt", "brt4_nopartype_lr0.05.rds"))

train_dat <- readRDS(file = here("data", "processed_data", "brt", "brt4_train_data.rds"))
test_dat <- readRDS(file = here("data", "processed_data", "brt", "brt4_test_data.rds"))

wc_ref <- read_csv(file = here("data", "worldclim_ref.csv"))
```

```{r}
preds <- predict.gbm(brt_mod, test_dat, n.trees = brt_mod$gbm.call$best.trees, type = "response")
tmp <- cbind(test_dat$pres, preds)
pres <- tmp[tmp[,1]==1, 2]
abs <- tmp[tmp[,1]==0, 2]
e <- evaluate(p = pres, a = abs)
e

roc_test <- pROC::roc(test_dat$pres, preds)
plot.roc(roc_test,
         xlim=c(1,0))
```

```{r}
summary(brt_mod)
gbm.plot(brt_mod, n.plots=12, plot.layout=c(3, 4), write.title = FALSE, common.scale = T)
gbm.plot(brt_mod, n.plots=12, plot.layout=c(3, 4), write.title = FALSE, common.scale = F)
#gbm.plot(brt_mod, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = F)
```



```{r}
pres_abs_without_host_train <- train_dat
brt4 <- readRDS(file = here("data", "processed_data", "brt", "brt4_nopartype_lr0.05.rds"))
summary(brt4)
gbm.plot(brt4, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T)
```


```{r}
pres_abs_without_host_train <- train_dat

gbm.plot(brt_mod, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T)

gbm.plot(brt_mod)
plot.gbm(brt_mod)
```


```{r}
inv <- pdp::partial(brt_mod, n.trees = brt_mod$n.trees, "spec_bin", prob = F, train = train_dat, recursive=F)
inv_alt <- pdp::partial(brt_mod, n.trees = brt_mod$n.trees, "spec_bin", prob = T, train = train_dat, recursive=F)
```


```{r}
make_plots <- function(model, var, bin_n = 40, y_fixed = F, y_axis) {
  
  data <- train_dat
  
  var_no <- which(colnames(data) %in% c(var))
  
  inv <- pdp::partial(model, n.trees=model$n.trees, var, prob = T, train = data, recursive = F)
  
  x_max <- max(data[var_no], na.rm=T)
  

  if(y_fixed==T){
    y_max = y_axis[2]
    y_min = y_axis[1]
  } else {
    y_max = max(inv$yhat)
    y_min <- min(inv$yhat)
  }
  
  
  plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
    geom_line(aes(x = .data[[var]], y = yhat),color=col,size=1) +
    xlim(0,x_max)+
    ylim(y_min,y_max)+
    ylab("PSR") +
    theme_minimal() +
    theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    theme(axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),axis.text=element_text(size=12))

  plot2 <- data %>%
  dplyr::select(.data[[var]]) %>%
  na.omit() %>%
  ggplot(aes(.data[[var]])) +
    geom_histogram(breaks = seq(0,x_max, x_max/bin_n), fill="gray") +
    #geom_histogram(fill="gray",binwidth=20) +
    scale_y_continuous(position = "right")+
    ylab("") +
    theme_minimal() +
    theme(axis.title.x = element_blank(),axis.text=element_text(size=12))#+
    #theme(plot.margin=unit(c(0,0,0,1.25),"cm"))
  
  plot1 <- add_sub(plot1,"")
  plot2 <- add_sub(plot2,var,size=12)
  
  list(pdp=plot1,histo=plot2)
}
```

```{r}
make_plots <- function(model, var, bin_n = 40, y_fixed = F, y_axis) {
  
  data <- train_dat
  
  var_no <- which(colnames(data) %in% c(var))
  
  inv <- pdp::partial(model, n.trees=model$n.trees, var, prob = T, train = data, recursive = F)
  
  x_max <- max(data[var_no], na.rm=T)
  

  if(y_fixed==T){
    y_max = y_axis[2]
    y_min = y_axis[1]
  } else {
    y_max = max(inv$yhat)
    y_min <- min(inv$yhat)
  }
  
  
  plot1 <- inv %>%
  na.omit() %>%
  ggplot(., aes(x = !!sym(var), y = yhat)) +
    geom_col(color=col,size=1) +
    ylim(y_min,y_max)+
    ylab("PSR") +
    theme_minimal() +
    theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    theme(axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),axis.text=element_text(size=12))

  plot2 <- data %>%
  dplyr::select(.data[[var]]) %>%
  na.omit() %>%
  ggplot(aes(.data[[var]])) +
    geom_histogram(fill="gray") +
    #geom_histogram(fill="gray",binwidth=20) +
    scale_y_continuous(position = "right")+
    ylab("") +
    theme_minimal() +
    theme(axis.title.x = element_blank(),axis.text=element_text(size=12))#+
    #theme(plot.margin=unit(c(0,0,0,1.25),"cm"))
  
  plot1 <- add_sub(plot1,"")
  plot2 <- add_sub(plot2,var,size=12)
  
  list(pdp=plot1,histo=plot2)
}
```

```{r}
pdp_draw <- function(mod1,mod2,mod3,mod4,mod5, hist_x=0.05, pdp_x=-0.03, hist_scale=0.95, pdp_scale=0.975, pdp_y=0.05){
  ggdraw()+
  draw_plot(mod1$histo, x=hist_x, scale = hist_scale) +
  draw_plot(mod1$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod2$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod3$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod4$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod5$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y)
  }
```

```{r}
spec_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "spec_bin", prob = T, train = train_dat, recursive = F)
type_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "ParMacroMicro", prob = T, train = train_dat, recursive = F)
mode_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "mode", prob = T, train = train_dat, recursive = F)
bio2_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "bio2", prob = T, train = train_dat, recursive = F)
area_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "area_km2", prob = T, train = train_dat, recursive = F)
prev_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "prev_bin", prob = T, train = train_dat, recursive = F)
bio13_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "bio13", prob = T, train = train_dat, recursive = F)
bio18_inv <- pdp::partial(brt_mod, n.trees=brt_mod$n.trees, "bio18", prob = T, train = train_dat, recursive = F)

  
```


```{r}
spec_pdp <- spec_inv %>% ggplot(., aes(x = spec_bin, y = yhat)) + geom_col(fill = "#440154") + theme_minimal() + 
  labs(x = "Phylogenetic \n Specialism (15.07%)", y = "Probability") + ylim(0, 0.075)

type_pdp <- type_inv %>% ggplot(., aes(x = ParMacroMicro, y = yhat)) + geom_col(fill = "#440154") + theme_minimal() + 
  labs(x = "Parasite \n Type (8.75%)", y = "Probability") + ylim(0, 0.075) + theme(axis.title.y = element_blank())


mode_pdp <- mode_inv %>% ggplot(., aes(x = mode, y = yhat)) + geom_col(fill = "#440154") + theme_minimal() + 
  labs(x = "Transmission \n Mode (8.09%)", y = "Probability") + ylim(0, 0.075)


bio2_pdp <- bio2_inv %>% ggplot(., aes(x = bio2, y = yhat)) + geom_line(size = 1, color = "#21918c") + theme_minimal() + 
  labs(x = "Mean Diurnal \n Range (7.39%)", y = "Probability") + ylim(0, 0.17) + theme(axis.title.y = element_blank())


area_pdp <- area_inv %>% ggplot(., aes(x = area_km2/1000, y = yhat)) + geom_line(size = 1, color = "#21918c") + theme_minimal() + 
  labs(x = "Size of Ecoregion \n (10^3 km^2)] (7.23%)", y = "Probability") + ylim(0, 0.17)


prev_pdp <- prev_inv %>% ggplot(., aes(x = prev_bin, y = yhat)) + geom_col(fill = "#440154") + theme_minimal() + 
  labs(x = "Prevalence (4.99%)", y = "Probability") + ylim(0, 0.075) + theme(axis.title.y = element_blank())


bio13_pdp <- bio13_inv %>% ggplot(., aes(x = bio13, y = yhat)) + geom_line(size = 1, color = "#21918c") + theme_minimal() + 
  labs(x = "Precipitation of \n wettest month (4.03%)", y = "Probability") + ylim(0, 0.17)


bio18_pdp <- bio18_inv %>% ggplot(., aes(x = bio18, y = yhat)) + geom_line(size = 1, color = "#21918c") + theme_minimal() + 
  labs(x = "Precipitation of \n warmest month (3.98%)", y = "Probability") + ylim(0, 0.17) + theme(axis.title.y = element_blank())


pdp_plots <- (spec_pdp + type_pdp) / (mode_pdp + bio2_pdp) / (area_pdp + prev_pdp) / (bio13_pdp + bio18_pdp)

ggsave(filename = here("figures", "pdp_plots.png"), pdp_plots, width = 4, height = 8)
```



relative influence
```{r}
brt_ri <- brt_mod$contributions

brt_ri %<>% left_join(., wc_ref)

brt_ri %<>% mutate(variable = ifelse(is.na(name), var, name))

brt_ri %<>% mutate(type = ifelse(is.na(type), "biotic", type)) %>%
  mutate(type = ifelse(variable == "area_km2", "abiotic", type))
```

```{r}
brt_ri %>% filter(type == "abiotic") %>% summarize(sum(rel.inf))
```


```{r}
ri_plot <- brt_ri %>%
  arrange((rel.inf)) %>%
  mutate(variable=factor(variable, levels=variable)) %>%
  ggplot(., aes(x = variable, y = rel.inf, fill = type)) + 
  geom_bar(position = "dodge", stat = "identity") +
    coord_flip()+
  ylim(0,16) +
  labs(title = "",
       fill = "Type") +
  xlab("") + 
  ylab("Relative Influence (%)") +
  scale_fill_manual(values = c("#21918c", "#440154")) +
  theme_minimal() +
  theme(legend.position = "none")


ggsave(filename = here("figures", "ri_plot.png"), ri_plot, width = 4, height = 8)
#ggsave(filename = here("figures", "legend.png"), ri_plot, width = 4, height = 8)
```





